### ISSUE TITLE
[5.14-OOB] Mbed TLS build issue with NUCLEO_F411RE

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-tls-socket#34] opened 2019-09-17 07:04 UTC
Mbed OS branch: `mbed-os-5.14.0-rc2`
Build command:
```
mbed compile --toolchain GCC_ARM --target NUCLEO_F411RE --clean
```

Build log:
```
Compile [  4.4%]: main.cpp
[Error] main.cpp@57,5: 'TLSSocket' was not declared in this scope
[Error] main.cpp@57,16: 'socket' was not declared in this scope
[Error] main.cpp@57,29: 'TLSSocket' does not name a type
[Warning] main.cpp@80,16: comparison between signed and unsigned integer expressions [-Wsign-compare]
[Error] main.cpp@102,12: type '<type error>' argument given to 'delete', expected pointer
[ERROR] ./main.cpp: In function 'int main()':
./main.cpp:57:5: error: 'TLSSocket' was not declared in this scope
     TLSSocket *socket = new TLSSocket;
     ^~~~~~~~~
./main.cpp:57:16: error: 'socket' was not declared in this scope
     TLSSocket *socket = new TLSSocket;
                ^~~~~~
./main.cpp:57:29: error: 'TLSSocket' does not name a type
     TLSSocket *socket = new TLSSocket;
                             ^~~~~~~~~
./main.cpp:80:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (result != size) {
         ~~~~~~~^~~~~~~
./main.cpp:102:12: error: type '<type error>' argument given to 'delete', expected pointer
     delete socket;
            ^~~~~~
```

**Comment by korjaa** [comment] 2019-09-17 07:06
IAR also fails with undeclared error
```
[Error] main.cpp@57,17: [Pe020]: identifier "TLSSocket" is undefined
[Error] main.cpp@57,30: [Pe020]: identifier "socket" is undefined
[Error] main.cpp@57,0: [Pe079]: expected a type specifier
[ERROR] 
      MBED_FORCEINLINE void attach(F &&func, float t)
      ^
"/home/jaakor01/workspace/mbed-os-example-tls-socket/mbed-os/drivers/Ticker.h",87  Warning[Pe606]: this pragma must immediately precede a declaration

      TLSSocket *socket = new TLSSocket;
      ^
"/home/jaakor01/workspace/mbed-os-example-tls-socket/main.cpp",57  Error[Pe020]: identifier "TLSSocket" is undefined

      TLSSocket *socket = new TLSSocket;
                 ^
"/home/jaakor01/workspace/mbed-os-example-tls-socket/main.cpp",57  Error[Pe020]: identifier "socket" is undefined

      TLSSocket *socket = new TLSSocket;
                              ^
"/home/jaakor01/workspace/mbed-os-example-tls-socket/main.cpp",57  Error[Pe079]: expected a type specifier
```

**Comment by korjaa** [comment] 2019-09-17 07:47
It seems my code doesn't compile because I don't have `TRNG` defined for `NUCLEO_F411RE`. This then causes my build to use [mbedtls/inc/mbedtls/config-no-entropy.h](https://github.com/ARMmbed/mbed-os/blob/f60e9a8075eaf2d284ef473a1f43501b5450b9a2/features/mbedtls/inc/mbedtls/config-no-entropy.h) instead of [mbedtls/inc/mbedtls/config.h](https://github.com/ARMmbed/mbed-os/blob/f60e9a8075eaf2d284ef473a1f43501b5450b9a2/features/mbedtls/inc/mbedtls/config.h).

**Comment by ciarmcom** [comment] 2019-09-17 11:59
*Internal Jira reference: https://jira.arm.com/browse/IOTCELL-2187*

**Comment by SeppoTakalo** [comment] 2019-09-17 15:39
F411 is not having entropy sources, and therefore cannot provide any security.

Why this is assumed to work?

**Comment by AnttiKauppila** [comment] 2019-09-18 06:22
It should not work. The problem is that compilation is failing for wrong failure. We should assert the compilation if TRNG is undefined.

**Comment by korjaa** [comment] 2019-09-18 06:47
Failing the build on missing TRNG would be the best option.

Also the project [README.md](https://github.com/ARMmbed/mbed-os-example-tls-socket/blob/master/README.md) does not define any requirements.

**Comment by AnttiKauppila** [comment] 2019-09-18 08:16
Fix + readme update: https://github.com/ARMmbed/mbed-os-example-tls-socket/pull/35

**Comment by AnttiKauppila** [comment] 2019-09-18 09:05
Fix has been merged

**Closed as completed by AnttiKauppila** 2019-09-18 09:05 UTC
Labels: mirrored, Jira status: CLOSED
